## Consider the below code to answer further questions:
    
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

In [1]:
import numpy as np

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#Ans: 1

Yes, there is a difference in the data type of variables list_ and array_list.

list_ is a Python list, while array_list is a NumPy array.

In [4]:
import numpy as np 

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object= list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [6]:
#Ans : 2

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

#Print the data type of each element in list_
for element in list_ :
    print(type(element))
    
#Print the data type of each element in array_list
for element in array_list : 
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q.3 Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list. 

Ans: 3

Yes, there will be a difference in the data type of the elements present in list_ and array_list.

because array_list is created with a dtype of int which will convert the string elements of the original list to integer type.
the data type of each element in list_ is str, while the data type of each element in array_list is numpy.int64 after conversion.

In [8]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

#print the data type of each element in list_
for element in list_ : 
    print(type(element))
    
#print the data type of each element in array_list
for element in array_list :
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
**(i) shape**

**(ii) size**

In [12]:
#Ans: (i)Shape:

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# find shape of num_array
shape = num_array.shape
print("Shape of num_array is:" , shape)

Shape of num_array is: (2, 3)


In [13]:
#(ii) Size :

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

#find size of num_array :
size = num_array.size
print("Size of num_array is:" , size)

Size of num_array is: 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

**[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [14]:
Ans: 5

zeros_array = np.zeros(shape= (3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?
**[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [15]:
Ans: 

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
